# image: https://hub.docker.com/r/prestashop/prestashop
# 

version: '3.8'

services:
  prestashop:
    image: prestashop/prestashop:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_PORT}:80
    volumes:
      - prestashop:/var/www/html
    environment:
      - PS_DEV_MODE=false
      - PS_DEMO_MODE=false
      #- PS_INSTALL_AUTO=1
      #- PS_DOMAIN=${APP_SITE_URL}:{APP_PORT}
      - PS_LANGUAGE=en
      - PS_COUNTRY=GB
      - PS_ALL_LANGUAGES=true
      - PS_FOLDER_ADMIN=admin
      - DB_SERVER=prestashop-mysql
      - DB_USER=${DB_MYSQL_USER}
      - DB_PASSWD=${DB_MYSQL_PASSWORD}
      - PS_ERASE_DB=0
      - PS_INSTALL_DB=0
      - DB_PREFIX=ps_
      - PS_HANDLE_DYNAMIC_DOMAIN=true
      - ADMIN_MAIL=${EMAIL}
      - ADMIN_PASSWD=${APP_PASSWORD}

    links: 
      - mysql
    restart: always

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_config/conf.d:/etc/mysql/conf.d
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
      name: ${APP_NAME}

volumes:
  prestashop:
